# Generated by Django 4.1 on 2022-08-25 05:17

import auth_api.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('admin', models.CharField(max_length=200, verbose_name='admin')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('rating', models.IntegerField(default=0, verbose_name='rating')),
                ('rating_count', models.BigIntegerField(default=0, verbose_name='rating count')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('equipments', models.ManyToManyField(blank=True, related_name='labs', to='booking_api.equipment')),
                ('experiments', models.ManyToManyField(blank=True, related_name='labs', to='booking_api.experiment')),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='auth_api.institute')),
            ],
        ),
        migrations.CreateModel(
            name='LabType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField(blank=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, verbose_name='end time')),
                ('day', models.CharField(choices=[('MO', 'MONDAY'), ('TU', 'TUESDAY'), ('WE', 'WEDNESDAY'), ('TH', 'THURSDAY'), ('FR', 'FRIDAY'), ('SA', 'SATURDAY'), ('SU', 'SUNDAY')], max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking_api.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('star', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='booking_api.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', auth_api.utils.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address')),
                ('research_field', models.CharField(blank=True, max_length=200, verbose_name='research field')),
                ('research_description', models.TextField(blank=True, verbose_name='research description')),
                ('qualification', models.CharField(default='', max_length=300, verbose_name='qualification')),
                ('designation', models.CharField(default='', max_length=300, verbose_name='designation')),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='auth_api.institute')),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='booking_api.labtype'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_api.lab')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_api.slot')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='auth_api.student')),
            ],
        ),
    ]
