# Generated by Django 4.1 on 2022-08-25 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('DP', 'DirectPay'), ('PC', 'PayViaCollege'), ('NA', 'NA')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('SU', 'SUCCESS'), ('PE', 'PENDING'), ('NA', 'NA')], default='NA', max_length=2),
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remarks', models.TextField()),
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booking_api.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SU', 'SUCCESS'), ('PE', 'PENDING'), ('RE', 'REJECTED')], default='PE', max_length=2)),
                ('type', models.CharField(choices=[('CI', 'CheckIn'), ('PC', 'PayViaCollege')], max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='booking_api.booking')),
                ('reciever_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_confirmation', to='auth_api.institute')),
                ('sender_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_bookings', to='auth_api.institute')),
            ],
        ),
    ]
